name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
      
    - name: Confirm Git identity
      run: |
        git config --global user.email "alan.ahmad@devoteam.com"
        git config --global user.name "alandevoteam"

#     - name: Nexus deploy snapshot
#       run: mvn clean deploy -DskipTests
      
#     - name: Nexus release prepare
#       run: mvn release:prepare -B -DskipTests=true -DscmCommentPrefix="[skip ci]"

#     - name: Nexus release perform
#       run: mvn release:perform -DskipTests -DscmCommentPrefix="[skip ci]"

#     - name: Run Terraform, set up Azure cloud infrastructure
#       run: |
#         cd ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/terraform
#         terraform init
#         terraform apply -auto-approve

    - name: Get warfile from Nexus repository
      run: |
        cd ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/
        wget http://localhost:8081/repository/maven-releases/org/springframework/samples/spring-framework-petclinic/5.3.9/spring-framework-petclinic-5.3.9.war

    - name: Prepare testing environment on VM
      run: ansible-playbook -i ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/inventory.ini ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/playbook_testing.yml

    - name: test environment created, start jmeter loadtest
      run: ~/jmeter/bin/jmeter -n -t ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/petclinic_loadtest_plan.jmx -l ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/file.jtl

    - name: No fallback, Jmeter loadtest passed, Prepare acceptance environment on VM
      run: ansible-playbook -i ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/inventory.ini ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/playbook_acceptance.yml

    - name: acceptance environment created, start selenium test, fallback if test fails
      run: python3 ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/seleniumtest.py
