name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Maven clean install
      run: mvn clean install -DskipTests
    
    - name: Nexus deploy snapshot
      run: mvn clean deploy -DskipTests
      
    - name: Confirm Git identity
      run: |
        git config --global user.email "alan.ahmad@devoteam.com"
        git config --global user.name "alandevoteam"
      
    - name: Nexus release prepare
      run: mvn release:prepare -B -DskipTests=true -DscmCommentPrefix="[skip ci]"

    - name: Nexus release perform
      run: mvn release:perform -DskipTests -DscmCommentPrefix="[skip ci]"

    - name: Prepare environment for testing & acceptance on Azure VM
      run: ansible-playbook -i ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/inventory.ini ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/playbook_testing.yml

    - name: jmeter loadtest
      run: /opt/jmeter/bin/jmeter -n -t ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/jmeter/petclinic_test_plan.jmx -l ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/jmeter/file.jtl

    - name: selenium test, add new owner and a new pet
      run: python3 ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/seleniumtest.py
      
    - name: Testing & acceptance completed, delete test-environment Azure VM
      run: |
        az network vnet delete --ids "/subscriptions/41e50375-b926-4bc4-9045-348f359cf721/resourceGroups/alan_ahmad-rg/providers/Microsoft.Network/virtualNetworks/test-vnet"
        az network nsg delete --ids "/subscriptions/41e50375-b926-4bc4-9045-348f359cf721/resourceGroups/alan_ahmad-rg/providers/Microsoft.Network/networkSecurityGroups/test-nsg"
        az network nic delete --ids "/subscriptions/41e50375-b926-4bc4-9045-348f359cf721/resourceGroups/alan_ahmad-rg/providers/Microsoft.Network/networkInterfaces/test-nic"
        az network public-ip delete --ids "/subscriptions/41e50375-b926-4bc4-9045-348f359cf721/resourceGroups/alan_ahmad-rg/providers/Microsoft.Network/publicIPAddresses/test-pip"
        az compute disk delete --ids "/subscriptions/41e50375-b926-4bc4-9045-348f359cf721/resourceGroups/ALAN_AHMAD-RG/providers/Microsoft.Compute/disks/testOsDisk"
        az compute vm delete --ids "/subscriptions/41e50375-b926-4bc4-9045-348f359cf721/resourceGroups/alan_ahmad-rg/providers/Microsoft.Compute/virtualMachines/testing-vm"
        az devtestlab schedule delete --ids "/subscriptions/41e50375-b926-4bc4-9045-348f359cf721/resourceGroups/alan_ahmad-rg/providers/Microsoft.DevTestLab/schedules/shutdown-computevm-testing-vm"

    - name: move production from local to cloud VM
      run: ansible-playbook -i ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/inventory.ini ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/ansible/playbook_prodenv.yml

