name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Maven clean install
      run: mvn clean install -DskipTests
    
    - name: Nexus deploy snapshot
      run: mvn clean deploy -DskipTests
      
    - name: Confirm Git identity
      run: |
        git config --global user.email "alan.ahmad@devoteam.com"
        git config --global user.name "alandevoteam"
      
    - name: Nexus release prepare
      run: mvn release:prepare -B -DskipTests=true -DscmCommentPrefix="[skip ci]"

    - name: Nexus release perform
      run: mvn release:perform -DskipTests -DscmCommentPrefix="[skip ci]"

    - name: setup test+acceptance environment
      run: ansible-playbook -i ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/inventory.ini ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/test_env.yml

    - name: jmeter loadtest
      run: /opt/jmeter/bin/jmeter -n -t ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/jmeter/petclinic_test_plan.jmx -l ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/jmeter/file.jtl

    - name: selenium test
      run: python3 ~/actions-runner/_work/github-petclinic/github-petclinic/src/test/seleniumtest.py

